development:
  adapter: postgresql
  encoding: utf8
  database: f4_development
  pool: 5
  username: f4
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: f4_test
  pool: 5
  username: f4
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: f4_production
  pool: 5
  username: f4
  password: